[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[logger]
level = "info"

[theme]
base = "light"

[ui]
# Ensure wide layout takes full width
hideTopBar = false
hideSidebarNav = false